### ISSUE TITLE
Transparent blocks

### ISSUE THREAD

**Issue by pl7y** [cgerikj/binary-greedy-meshing#20]
Hello, it seems from the code that only solid blocks are treated. 

If one has a glass block next to a dirt block, the inside faces between glass and dirt are culled:

<img width="485" alt="image" src="https://github.com/cgerikj/binary-greedy-meshing/assets/10465876/c66e8a8a-988b-4fb0-90b3-18e71d380047">

How can I disable culling between transparent and non-transparent blocks?

**Comment by cgerikj** [comment]
Hi! Sorry for the late reply.

This mesher doesn't have built in support for transparency but it can be modifed / extended to support it. 

You could treat the transparent blocks as air when meshing the solid blocks. To do this, you have to modify how the occupancy mask is built. This way you'll get one mesh that only contain solid blocks and no transparent blocks.

If you want to use this mesher for transparent blocks too, that's a bit trickier because you have to create a separate modified mesher that changes how the occupancy mask is built and also how the culling works (if you want to cull faces of transparent blocks that face solid blocks).
