### ISSUE TITLE
Help on implementing non-cubic chunk sizes

### ISSUE THREAD

**Issue by Ayliroe** [cgerikj/binary-greedy-meshing#5]
Hi, amazing algorithm! Truly lightspeed-fast.

Do you have any tips on how to refactor the CS_P/CS_P2/CS_P3 variables to allow for chunks of mismatched width/height?
I'm familiar with other greedy meshing systems that allow for dynamic chunk sizes, by switching to the axis' dimension being worked on in such a way:

	for (int Axis = 0; Axis < 3; ++Axis) {

		int Axis1 = (Axis + 1) % 3;
		int Axis2 = (Axis + 2) % 3;

		int Size0 = Size[Axis];
		int Size1 = Size[Axis1];
		int Size2 = Size[Axis2];

		for (int j = 0; j < Size2; ++j) { ... }

And to get the block values as a linear array:

	int GetID() { return Z * Size.X * Size.Y + Y * Size.X + X; }

However your code is especially abstract, so I have difficulties seeing where to properly reformat without breaking everything.

**Comment by cgerikj** [comment]
Closed since I never replied to this..

Let me know if you still want me to take a look. The short answer is that it probably can't easily be modified to support non-cubic chunks but you can feed it cubic parts of non-cubic chunks if that makes sense? 64x64x64 parts of a 64x64x256 chunk for example.
